apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: database-persistent-volumn-claim
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi